name: Status of implicit dependencies affects job flow

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print information
        run: echo "Hello world"

  skipped-job:
    runs-on: ubuntu-latest
    needs: greet
    if: failure()
    steps:
      - name: Print information
        run: echo "This will always be skipped, since first job will not fail"

  forced-job:
    runs-on: ubuntu-latest
    needs: skipped-job
    if: always()
    steps:
      - name: Print information
        run: echo "This will always run"

  implicitly-skipped:
    runs-on: ubuntu-latest
    needs: forced-job
    steps:
      - name: Print information
        run: echo "This will be skipped because the implicit dependency, skipped-job, will always be skipped"

  also-implicitly-skipped:
    runs-on: ubuntu-latest
    needs: forced-job
    if: needs.forced-job.result == 'success'
    steps:
      - name: Print information
        run: echo "This will still be skipped because an implicit dependency was skipped"

  forced-not-skipped:
    runs-on: ubuntu-latest
    needs: forced-job
    if: always()
    steps:
      - name: Print information
        run: echo "This will not be skipped, as it is forced"

  forced-with-status-not-skipped:
    runs-on: ubuntu-latest
    needs: forced-job
    if: always() && needs.forced-job.result == 'success'
    steps:
      - name: Print information
        run: echo "This will not be skipped, since the forced job will be successful"
  
  forced-with-status-skipped:
    runs-on: ubuntu-latest
    needs: forced-job
    if: always() && needs.forced-job.result == 'failure'
    steps:
      - name: Print information
        run: echo "This will be skipped, since the forced job will not fail"
